input:
  kafka:
    addresses:
      - redpanda:9092
    topics:
      - coinbase_ticker
    consumer_group: redis-sink-group

pipeline:
  processors:
    - mapping: |
        root = this
        meta redis_key = "ticker:" + this.product_id.or("unknown") + ":" + now().ts_unix().string()

output:
  redis_hash:
    url: redis://redis:6379/1
    key: ${! meta("redis_key") }
    fields:
      product_id: ${! this.product_id }
      price: ${! this.price }
      time: ${! this.time }
      volume_24h: ${! this.volume_24h }
      best_bid: ${! this.best_bid }
      best_ask: ${! this.best_ask }
